remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll
title:              Typekast
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Typekast
baseurl:            "/"
url:                "https://typekast.github.io/"

# Social Profiles
twitter_username:   typekast 
github_username:    typekast 
facebook_username:  typekast
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
