remote_theme: typekast/startbootstrap-clean-blog-jekyll
title:              Typekast
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Typekast
baseurl:            "/"
url:                "https://typekast.github.io/"

# Social Profiles
twitter_username:   typekast 
github_username:    typekast 
facebook_username:  typekast
instagram_username: typekast.io
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Meta tags configuration
meta_image: "/img/bg-index.jpg"
meta_image_width: 200
meta_image_height: 200
meta_locale: "pt_BR"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
