remote_theme: typekast/startbootstrap-clean-blog-jekyll
title:              Typekast.io
email:              typekast.io@gmail.com
short_description:  Propagando conhecimento tecnológico.
description:        Typekast.io é um blog que tem como objetivo propagar conhecimento sobre desenvolvimento de software e tecnologia.
author:             Typekast.io
baseurl:            "/"
url:                "https://typekast.github.io"
podcast_url:        https://anchor.fm/saifora

# Social Profiles
twitter_username:   typekastio
github_username:    typekast 
facebook_username:
instagram_username: typekast.io
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Meta tags configuration
meta_image: "/img/bg-index.jpg"
meta_image_width: 200
meta_image_height: 200
meta_locale: "pt_BR"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
